# Site settings
title: Bata Loop Pak
subtitle: Calibrated, hand forged bits & pixels
email: my_email@nobots.bot
description: Personal place to post & debate subjects that I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://batalooppak.github.io" # the base hostname & protocol for your site

twitter_username: bottybot
github_username:  batalooppak

highlighter: rouge

# Build settings
markdown: kramdown
